# Generated by Django 5.2.8 on 2025-11-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="has_experience",
            field=models.BooleanField(
                default=False, verbose_name="Есть опыт содержания животных"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="has_other_pets",
            field=models.BooleanField(
                default=False, verbose_name="Есть другие питомцы"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="ready_for_pet",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Готовность к питомцу",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("volunteer", "Волонтёр"),
                    ("adopter", "Усыновитель"),
                ],
                default="adopter",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, unique=True, verbose_name="Ссылка (slug)"
            ),
        ),
    ]
