# Generated by Django 5.2.8 on 2025-11-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(blank=True, max_length=100, null=True)),
                ("age_years", models.PositiveIntegerField(default=0)),
                ("age_months", models.PositiveIntegerField(default=0)),
                ("health_status", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("in_shelter", "В приюте"), ("adopted", "Усыновлено")],
                        default="in_shelter",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_url", models.ImageField(upload_to="animals/%Y/%m/%d")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
