# Generated by Django 5.2.8 on 2025-11-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={
                "ordering": ["name"],
                "verbose_name": "Животное",
                "verbose_name_plural": "Животные",
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание/характер"
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, unique=True, verbose_name="Ссылка (slug)"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="age_months",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Возраст (месяцы)"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="age_years",
            field=models.PositiveIntegerField(default=0, verbose_name="Возраст (годы)"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Порода"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="health_status",
            field=models.TextField(verbose_name="Состояние здоровья"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.CharField(max_length=50, verbose_name="Вид"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[("in_shelter", "В приюте"), ("adopted", "Усыновлено")],
                default="in_shelter",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
