# Generated by Django 5.2.8 on 2025-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("feeding", "Кормление"),
                            ("medical", "Медосмотр"),
                            ("cleaning", "Уборка"),
                            ("event", "Мероприятие"),
                            ("news", "Новости"),
                            ("advice", "Совет по уходу"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="activities/%Y/%m/%d"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
