# Generated by Django 5.2.8 on 2025-11-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Активность приюта",
                "verbose_name_plural": "Активности приюта",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("feeding", "Кормление"),
                    ("medical", "Медосмотр"),
                    ("cleaning", "Уборка"),
                    ("event", "Мероприятие"),
                    ("news", "Новости"),
                    ("advice", "Совет по уходу"),
                ],
                max_length=20,
                verbose_name="Тип активности",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="photo_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="activities/%Y/%m/%d",
                verbose_name="Фото (опционально)",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
