# Generated by Django 5.2.8 on 2025-11-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adoptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adoptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="adoption",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_record",
                to="adoptions.adoption",
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="processed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adoption",
            unique_together={("user", "animal")},
        ),
    ]
