# Generated by Django 5.2.8 on 2025-11-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0002_initial"),
        (
            "animals",
            "0002_alter_animal_options_animal_description_animal_slug_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adoption",
            options={
                "verbose_name": "Заявка на усыновление",
                "verbose_name_plural": "Заявки на усыновление",
            },
        ),
        migrations.AlterModelOptions(
            name="return",
            options={
                "verbose_name": "Возврат животного",
                "verbose_name_plural": "Возвраты животных",
            },
        ),
        migrations.AlterField(
            model_name="adoption",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adoptions",
                to="animals.animal",
                verbose_name="Животное",
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="rejection_reason",
            field=models.TextField(verbose_name="Причина отклонения"),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                    ("returned", "Возвращено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата подачи заявки"
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adoptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="adoption",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_record",
                to="adoptions.adoption",
                verbose_name="Заявка",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="processed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_returns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обработал",
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="reason",
            field=models.TextField(verbose_name="Причина возврата"),
        ),
        migrations.AlterField(
            model_name="return",
            name="returned_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата возврата"),
        ),
    ]
